name: WedBars
version: 1.0_b2_u22
main: com.blockhead7360.mc.wedbars.WedBars
author: Blockhead7360
description: It's like Bed Wars on Hypixel but better I swear
website: https://github.com/dilanx/WedBars
depend: [HolographicDisplays]

commands:
  wedbars:
    description: Information about Wed Bars
    aliases: [wb]
  load:
    description: Loads a given arena.
  setup:
    description: Enter the arena setup wizard.
  team:
    description: Assign a player to a team.
  start:
    description: Starts the game.
  test:
    description: Test?
  itemshop:
    description: Opens the item shop, for use with NPCs.
  teamshop:
    description: Opens the team shop, for use with NPCs.
permissions:
  wedbars.itemshop:
    default: false
  wedbars.admin:
    default: op