# Sets the max build height for players during the game (int, in blocks) default: 90
maxBuildHeight: 90

# Sets the fuse time for tnt once placed (int, in ticks) default: 60
tntFuse: 60

# The y-level where any player at it or below will be considered "in the void"
# and killed. (int, y-level) default: 0
voidLevel: 0

# How many diamonds that have yet to be picked up can sit in a generator at once.
# (int, number of diamonds) default: 4
maxDiamondsInGen: 4

# How many emeralds that have yet to be picked up can sit in a generator at once.
# (int, number of emeralds) default: 2
maxEmeraldsInGen: 2

# How long the player will have to wait before being respawned if their bed is
# not broken. (int, seconds * 10) default: 50 (5 seconds)
respawnTime: 50

# How long the game will wait after the end of a game before starting the arena
# reset process. (int, seconds) default: 10
timeBeforeReset: 10

# Powerup: Golems
# You can set how much time golems live for (int,seconds), their targeting range
# (int, radius blocks), and their health (int, hitpoints).
# default life: 240, default range: 7, default health: 20
golemLife: 240
golemTargetDistance: 7
golemHealth: 20

# Powerup: Bugs
# You can set how much time bugs live for (seconds), their targeting range
# (int, radius blocks), and their health (int, hitpoints).
# default life: 120, default range: 4, default health: 8
bugLife: 120
bugTargetDistance: 4
bugHealth: 8

# Powerup: Bridge Eggs
# Set the max time eggs will be live for. (int, seconds * 10)
# Default: 30
eggTime: 30

# MySQL database information (required for stats)
mysql:
  enabled: false
  host: None
  database: None
  user: None
  pass: None