# Welcome, fellow server admin, to the CONFIG ZONE. Here you can tweak many aspects
# of the game to your liking. If something gets messed up, just delete the file and
# the plugin will generate a new one on startup. For help with WedBars, see our
# documentation: https://github.com/dilanx/WedBars/blob/main/DOCUMENTATION.md

# Sets the fuse time for tnt once placed (int, in ticks) default: 60 (3 seconds)
tntFuse: 60

# The y-level where any player at it or below will be considered "in the void"
# and killed. (int, y-level) default: 0
voidLevel: 0

# How many diamonds that have yet to be picked up can sit in a generator at once.
# (int, number of diamonds) default: 4
maxDiamondsInGen: 4

# How many emeralds that have yet to be picked up can sit in a generator at once.
# (int, number of emeralds) default: 2
maxEmeraldsInGen: 2

# How many blocks from each island spawn should be unmodifiable by players.
# (int, radius in blocks) default: 5
spawnProtection: 5

# Half of box centered around bed where enemy players trigger traps.
# (int, radius in blocks) default: 7
trapDistance: 7

# How long the player will have to wait before being respawned if their bed is
# not broken. (int, seconds) default: 5
respawnTime: 5

# How long the game will wait after the end of a game before starting the arena
# reset process. (int, seconds) default: 10
timeBeforeReset: 10

# How long the game should count down in the lobby before the game begins (int, seconds)
# default: 10
lobbyStartTime: 10

# Powerup: Golems
# You can set how much time golems live for (int,seconds), their targeting range
# (int, radius blocks), and their health (int, hitpoints).
# default life: 240, default range: 7, default health: 20
golemLife: 240
golemTargetDistance: 7
golemHealth: 20

# Powerup: Bugs
# You can set how much time bugs live for (seconds), their targeting range
# (int, radius blocks), and their health (int, hitpoints).
# default life: 120, default range: 4, default health: 8
bugLife: 120
bugTargetDistance: 4
bugHealth: 8

# Powerup: Bridge Eggs
# Set the max time eggs will be live for. (int, seconds)
# Default: 3
eggTime: 3

# MySQL database information (required for stats)
# More info on this can be found at https://github.com/dilanx/WedBars/blob/main/DOCUMENTATION.md#player-statistics
mysql:
  enabled: false
  host: None
  database: None
  user: None
  pass: None